# Generated by Django 4.2.2 on 2023-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_image/'),
        ),
    ]
