# Generated by Django 4.2.2 on 2024-01-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aprroved',
            field=models.BooleanField(default=False, verbose_name='Aprroved'),
        ),
    ]
