# Generated by Django 4.2.2 on 2024-01-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_aprroved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
