# Generated by Django 4.2.2 on 2024-01-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_aprroved_event_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='approved',
            new_name='aprroved',
        ),
    ]
